apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-k7k8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-k7k8@sha256:3fa3e1e3a6955e369ee70cc4d18832203998697b67b310e5201aa57287edc39b
        name: my-nodejs
        resources: {}
status: {}
